- Rmd/DESeq2_report.rnaseq.Rmd
- Rmd/Sample_QC.Rmd
- scripts/R-ODAF_sequencing_DataPreprocessing.sh
Various bug fixes for edge cases that caused errors.
Main thing changed here is the Sample QC script - altered the plotting of plates by row and column. Should be more robust (at least not case sensitive).
> Sample qc improvements

- Rmd/DESeq2_report.rnaseq.Rmd
- Rmd/Sample_QC.Rmd
Wanted to flag some important changes here...
1) most importantly, there was an edge case (or maybe not edge case...) where the way columns were selected for checking spikes, relevance filtering, and the quantile rule was not getting the correct samples, leading to way higher numbers of genes being filtered.
2) to help troubleshoot things I've been migrating some stuff to plotly - the PCAs (makes it easier to identify outlier samples by name) and gene plots.
3) gene plots now also have a somewhat convoluted (but as far as I can see, one of the only ways in a static HTML format) method for selecting from the top ~1000 genes by fold change to plot in boxplot format, similar to the static gene plots. Mainly useful for dose-response modeling studies, but pretty helpful when people want to see …
> Bisphenols

- Rmd/DESeq2_report.rnaseq.Rmd
- Rmd/Pathway_analysis.Rmd
- Rmd/Sample_QC.Rmd
- scripts/render_DESeq2_report.R
Fixes a bunch of minor issues with plots and adds some new ones.
> Improvements to plotting

- Rmd/DESeq2_report.rnaseq.Rmd
- Rmd/Sample_QC.Rmd
- install.sh
- scripts/render_DESeq2_report.R
- makes a DEG table file
- skips groups with N of 1 properly now
- manually exclude files (eg cytotoxic samples) in QC script (still needs work for better use... but does the job)
> Some bug fixes and extra functionality

- Rmd/DESeq2_report.rnaseq.Rmd
Make 3 result lists:
- all genes
- all genes passing R-ODAF filters
- significant results
> Fix BMDexpress input

- Rmd/DESeq2_report.rnaseq.Rmd
I didn't want to commit straight to main in case you were working on something but for some reason I missed a change when I implemented those resList changes
> change resList in Rmd to ResListALL

- Rmd/DESeq2_report.rnaseq.Rmd
- Rmd/Sample_QC.Rmd
- scripts/utilities/DEG_summary_plot.R
Bugfixes for sample QC: improve manual sample removal workflow; explicitly set names to reorder sample data (this has probably screwed up some stuff at some point, but not too severely, just some data vis probably)
Should also close #25
> Sample QC bugfixes

- README.md
- Rmd/DESeq2_report.rnaseq.Rmd
- Rmd/Sample_QC.Rmd
- scripts/utilities/DEG_summary_plot.R
Made a skeleton of documentation to work with
> Documentation, DEG summary figure

- Rmd/DESeq2_report.rnaseq.Rmd
- config/config.default.yaml
- scripts/setup_functions.R
Fixes issues #55 #58 and #59 
Thanks to @johndhstead for identifying them
Not tested extensively but should be pretty straightforward fixes.
> Fix issues 55 58 59

- workflow/Snakefile.temposeq
> Disable adapter trimming; pipe fastp output to STAR input

- install.R
> add stuff to install.R

- scripts/summarize_across_facets.R
Add a script to summarize # DEGs, filter stats across facets and contrasts.
Still TBD: ok for this to be just a couple of plots or should I make an R markdown report?
> add summarization script

- scripts/summarize_across_facets.R
> sort summarization plots by contrasts

- Rmd/DESeq2_report_new.Rmd
> Rotate x axis labels properly in gene count plots

- Rmd/DESeq2_report_new.Rmd
> plot gene names on DEG heatmap if they fit, also consolidate some heatmap code

- scripts/render_DESeq2_report.R
- scripts/run_DESeq2.R
- scripts/setup_functions.R
in progress
fixes #98 
This is mostly a Kate's quality of life change, since I forget to set things a lot. Whether it's useful or we just forget to keep the 'required params' list up to date remains to be seen.
> Add check for required params

- Rmd/DESeq2_report_new.Rmd
Should get rid of crosstool requirement--right? Or do I have to swap the genes one too...
Done and ready for review. Note that I kept the old version in the code for the review but I'll delete that before I merge.
> add new plotly plot for volcanos

- Rmd/Sample_QC.Rmd
- config/config.default.yaml
- scripts/DESeq_functions.R
- scripts/file_functions.R
- scripts/run_DESeq2.R
- scripts/write_output_tables.R
This should generate the output that Andrew makes to give to collaborators for analysis, need to double check with him that it's been filtered properly though.
> Write filtered output to file for biosets input

- scripts/file_functions.R
- scripts/run_DESeq2.R
- scripts/write_output_tables.R
When `write_additional_output` is TRUE in config, generates a bunch of files (one per dose) of genes + pvals.
> Add a chunk to produce the biosets input

- .github/workflows/tests.yml
- Rmd/DESeq2_report_new.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/extra_stats_report.Rmd
- Rmd/go_pathway_report.Rmd
- config/config.default.yaml
- environment.yml
- scripts/render_DESeq2_report.parallel.R
- scripts/write_output_tables.R
Seems to be passing tests! But needs work on the stats report, both to solve the memory bug and to fix up the faceting work I drafted. Try it out!
> Parallel processing fixes

- Rmd/DESeq2_report_new.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/extra_stats_report.Rmd
- Rmd/go_pathway_report.Rmd
- scripts/render_DESeq2_report.R
- scripts/render_DESeq2_report.parallel.R
- scripts/run_DESeq2.R
- scripts/setup_functions.R
- scripts/summarize_across_facets.R
At least for Tempo-seq experiments, this should fix the bug that was causing gene names to be displayed as NA in heatmaps
> fix NA bug

- Rmd/DESeq2_report_new.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/go_pathway_report.Rmd
- Rmd/stats_report.Rmd
- config/config.default.yaml
- environment.yml
- scripts/DESeq_functions.R
- scripts/file_functions.R
- scripts/render_DESeq2_report.parallel.R
- scripts/run_DESeq2.R
- scripts/write_output_tables.R
This could be merged quickly with little consequence. Ready for review
> Stats report tweaks

- Rmd/DESeq2_report_new.Rmd
- Rmd/Sample_QC.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/go_pathway_report.Rmd
- Rmd/stats_report.Rmd
- scripts/DESeq_functions.R
- scripts/data_functions.R
- scripts/file_functions.R
- scripts/load-facet-data.R
- scripts/render_DESeq2_report.parallel.R
- scripts/run_DESeq2.R
- scripts/setup_functions.R
> Changes to variable names

- scripts/render_studywide_QC_report.R
- scripts/write_output_tables.R
There were NAs because the join was done on DEGs instead of all genes.
Typo in branch name... whatever I guess
> Minor fix to output tables

- Rmd/go_pathway_report.Rmd
- environment.yml
Pretty simple
Also included the dependencies that weren't added by the enrichplot package...
> Fixes GO plots

- Rmd/DESeq2_report_new.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/references.bib
- Rmd/stats_report.Rmd
- scripts/DESeq_functions.R
- scripts/data_functions.R
- scripts/load-facet-data.R
- scripts/render_DESeq2_report.parallel.R
- scripts/run_DESeq2.R
- scripts/summarize_across_facets.R
Several changes:
- added the methods stub paragraph and the references back into the main DEseq report, and added a methods stub to the QC report. This necessitated saving some metadata (sample counts) from the DEseq script, so it was a teeny bit more complicated
- make summarize_across_facets.R work better in the case of one facet
- A few tweaks to make things prettier for RNA-seq (gene names vs features IDs etc)
I think that's it
> Updates related to Qutob UV RNA-seq project

- scripts/render_DESeq2_report.parallel.R
- scripts/run_DESeq2.R
> copy config and contrasts to Rdata folder after report generation

- .gitignore
- Rmd/DESeq2_report_new.Rmd
- Rmd/Sample_QC.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/go_pathway_report.Rmd
- Rmd/stats_report.Rmd
- config/config.default.yaml
- scripts/DESeq_functions.R
- scripts/file_functions.R
- scripts/run_DESeq2.R
- scripts/write_output_tables.R
- workflow/Snakefile
Add an option to overwrite the DESeq2 formula via config file.
A few bugfixes added as well.
> Formula override

- workflow/Snakefile
Hi Matthew,
Finally managed to push a fresh PR directly on the main repo. 
Here are some suggested changes for minor corrections (unused commas and imports) + I think what could fix the pipe() issues. There were several locations where the number of threads differed between rules (either workflow.cores or pipeline_config['threads']). I propose to standardize the number of threads across the snakefile using workflow.cores.
> Minor corrections

- workflow/envs/reports.yml
> Freeze r-matrixstats version

- .github/workflows/build.yml
- .github/workflows/tests.yml
Good grief this better be the last one
> Build container

- scripts/DESeq_functions.R
> hardcode linear FC to 1.2 for biosets filtering

- Rmd/DESeq2_report_new.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/go_pathway_report.Rmd
- Rmd/stats_report.Rmd
- scripts/DESeq_functions.R
- scripts/setup_functions.R
- scripts/write_output_tables.R
- workflow/schema/config.schema.yaml
Fixes #180 
Linear fold change filter is now a parameter in the config file instead of being buried in the code.
Linear FC filter for significant DEGs (default 1.5) is now separated from linear FC filter for biosets as requested by Chris Corton of EPA (default 1.2).
> Add config params

- Rmd/data_explorer_report.Rmd
Fix problem with replicated points in by-gene interactive plots.
Order x-axis of by-gene interactive plots so they go by dose.
> Fix explorer plots

- Dockerfile
Just trying to get the conda environment packages to print during build.yml workflow so we can figure out why tests pass but builds fail.
> add conda package listing try2

- Dockerfile.new
I just want to see the darn package lists.
> print conda env packages during build try2

- workflow/modules/3-align.smk
Just adding printed statements about existence of directories so I can troubleshoot our bizarre issues when running the container on Azure.
> add test for align_dir in rule STAR

- workflow/modules/3-align.smk
Azure batch runs error out with this issue:
Shared memory error: 4, errno: Invalid argument(22)
EXITING because of FATAL ERROR: problems with shared memory: error from shmget() or shm_open().
SOLUTION: check shared memory settings as explained in STAR manual, OR run STAR with --genomeLoad NoSharedMemory to avoid using shared memory
This merge is based on changes from snakemake_cloud branch to deal with the shared memory problem. Code will check if running on Azure, and if so, won't load the STAR index to memory. Nothing should change when running locally.
> don't load STAR genome to memory on Azure

- scripts/render_DESeq2_report.parallel.R
Adds back the "hasDEGs" check when rendering reports, so reports are only attempted for facets that have significant DEGs. Without this code, the empty dataframes from DEG-free facets cause errors that break the pipeline.
> Only make reports for facets with DEGs

- R.ODAF.utils/R/get_contrasts.R
- Rmd/DESeq2_report_new.Rmd
- Rmd/Sample_QC.Rmd
- Rmd/data_explorer_report.Rmd
- Rmd/go_pathway_report.Rmd
- Rmd/stats_report.Rmd
- Rmd/tgx_ddi.Rmd
- inputs/config/config.default.yaml
- scripts/render_DESeq2_report.parallel.R
- scripts/run_DESeq2.R
- workflow/modules/1-define.smk
- workflow/schema/config.schema.yaml
Make or update parameters in the config file, including:
- metadata_file and contrasts_file, so different file names can be used. This will improve organization and documentation on complex projects, where we previously just overwrote metadata.txt and contrasts.txt. Closes issue #233 .
- add bioinformatician_name, so reports will show who ran the analysis
- change project_name to researcher_name, for clarity
Also adds a check that the contrasts file is properly set up, and throws an error if it's not. Closes issue #239
Allows biospyder params to be set to null when running RNA-seq analysis. Closes issue #237 .
> Config update

- R.ODAF.utils/R/write_reports.R
- Rmd/tgx_ddi.Rmd
- scripts/render_DESeq2_report.parallel.R
Now a single CSV file file is output summarizing the DDI or non-DDI calls across all reports. 
Closes issue #243 .
Tests currently failing because PR #246 is not yet approved and merged.
> tgx-ddi summary csv

- .gitignore
- Rmd/Sample_QC.Rmd
Fixes issue #245 . Maybe.
Before merging I would like to try and deal with issue #235 as well.
> fix QC report issues

- Rmd/Sample_QC.Rmd
Significantly re-arranged the Studywide QC report to make it more user-friendly and intuitive. Added a PCA plot.
> Update qc report

- .github/workflows/rnatests.yml
- .github/workflows/temposeqtests.yml
Deals with changes to the test data repo: reorganization of temposeq test data and addition of rna-seq test data.
> Add rna test data workflow

- R.ODAF.utils/R/summarize_across_facets.R
- Rmd/Sample_QC.Rmd
- Rmd/summary_report_new.Rmd
- scripts/render_DESeq2_report.parallel.R
- workflow/envs/reports.yml
Correctly order contrasts by dose (ex. 0.1, 0.5, 1, 5, 10 instead of 0.1, 0.5, 1, 10, 5) in both the DEG table and the bar plots.
Add group dendrogram row to criteria table.
> Fixes for summary report
