R-ODAF/R-ODAF_Health_Canada

Rmd/DESeq2_report.rnaseq.Rmd
Rmd/Sample_QC.Rmd
scripts/temposeq/temposeq_quantification.R
workflow/Snakefile

* Multithreading improvements
* Change over all files to TSV, removing need for sampledata_sep
* Several parameters from the config had accidentally been removed from Rmd files, added back in this PR
* Got tired of being asked about read counts - made some boxplots and table showing summary stats (also mostly available in MultiQC report, but the Study wide QC now reports mean and median values for the study for read #, aligned %, etc.).

Updates to Snakefile and bug fixes; TSV file improvements; Summary stats in QC

---

Rmd/DESeq2_report_new.Rmd
scripts/DESeq_functions.R

fixes #85
Wasn't using the pre-filtered `significantResults` properly, so I fixed that and shrunk the plots so they're a little prettier.

size / warnings for by gene plots

---

Rmd/data_explorer_report.Rmd

Note that this makes two other tweaks to the tables:
- I hid the unadjusted pvalue (to make room for the URLs)
- I left in some other columns (hidden) that might be useful for users to download, e.g. gene symbol on its own

Add urls column to data table with both NCBI and Ensembl links

---

Dockerfile

Took an initial version of @mattjmeier's Dockerfile and tried to adapt it to work.
Image builds nicely, and launches a bash shell at start, dropping you into /home/R-ODAF with a conda context. Still need to run `conda activate R-ODAF` before doing anything, but passing in a shell script that you want to execute for a run should be possible, and probably required if this was run using Azure Batch anyway.

Initial Docker image build

---

README.md
Rmd/Sample_QC.Rmd
config/config.default.yaml

1. Adds a heatmap to the QC report showing genes with zero counts. Could be illustrative in certain failure states.
For cases where there are >3000 genes (ie whole genome tempo-seq or RNA-seq), it plots a random 2500-gene subset.
2. Adds some plots summarizing the GC content of the data (for TempO-Seq only).

Add zero counts heatmap + GC content plots

---

scripts/DESeq_functions.R

Fixes a bug that was introduced in 111c22c that mis-selected columns when calculating count values for the spike filter, rendering it essentially random 😶 Because spike-filtered genes are _fairly_ rare, this shouldn't majorly affect most analyses.

Fix column selector for spike filter

---

workflow/envs/preprocessing.yml

MultiQC v1.12 gets error if run in environment with python 3.12. Sticking with python v3.11 fixes this problem and doesn't cause others (for now).

pin python version 3.11 so that MultiQC v1.12 works

---

scripts/DESeq_functions.R
scripts/data_functions.R
scripts/render_DESeq2_report.parallel.R

These commits stop the analysis from breaking if 
- the formula_override config parameter is null
- facets parameter is null
- the facet value(s) aren't in the contrasts file (ex. facets are "A" and "B"; current code requires that the contrasts be something like:
A_10 A_0

Small fixes for faceting and formula_override problems

---

scripts/data_functions.R
scripts/setup_functions.R
workflow/modules/1-define.smk
workflow/schema/config.schema.yaml

Now if anyone is foolish enough to include the faceting column in the intgroups_to_plot list in the config parameters, the analysis will be stopped and a helpful message will print so that troubleshooting takes less than 3 days.
There are checks in the snakemake code (module 1) and in the R code for anyone who runs with Rscript, independent of Snakemake.
Snakemake also checks whether the reference files specified in the config exist before starting the analysis.
Tests aren't running atm. I think we wore out all the github runners.

Add checks (intgroup_to_plot list, existence of ref files)

---

.github/workflows/tests.yml
.gitignore

Add conda list commands so we can see the contents of environments installed during snakemake workflow during github actions.

Print conda env contents during tests

---

Dockerfile.new

Added a conda list section to Dockerfile.new instead of Dockerfile (Dockerfile.new is used in build.yml). Reverted commits that edited Dockerfile. Curious to see what happens with the previous merges.

print conda env packages during build

---

.github/workflows/build.yml
Dockerfile.new

Now we're adding a Run command in Docker image just to print a file containing the conda envs package lists. I am not optimistic.

print conda env packages during build try3

---

Dockerfile
Dockerfile.new

Tidying up the docker files after my failed attempts at printing conda environments for troubleshooting purposes. Shouldn't change any functionality.

remove nonfunctional troubleshooting code

---

workflow/modules/3-align.smk

It turns out the AZ_BATCH variable I originally chose isn't there in all tasks. Bad luck.
New code searches for AZ_BATCH_POOL_ID, which should always be present when running on Azure. Also removes unnecessary print statements from troubleshooting the disappearance of output/processed/aligned directory on Azure.

use azure envvar that is in all tasks

---

.gitignore
Rmd/Sample_QC.Rmd
inputs/config/config.default.yaml
workflow/schema/config.schema.yaml

Adds a quality control step, analogous to the current dendrogram tree height cutoff, but working with trees within each treatment_var group instead of the project as a whole. The config parameter for the within-group trees can be set to null to skip this step and run the QC as normal. 
This is helpful for projects where some treatment groups are quite different from the rest in the project, which would cause that group to be considered an outlier in the studywide-tree, even though it really is biologically distinct. In that case, the studywide-tree height cutoff can be loosened, and the group-tree threshold used to remove outliers instead.

Qc group dendro cutoffs

---

.github/workflows/tests.yml
R.ODAF.utils/R/get_metadata.R
Rmd/Sample_QC.Rmd
scripts/render_DESeq2_report.parallel.R
scripts/run_DESeq2.R

Now metadata.QC_applied.txt goes in the output/QC folder instead of inputs/metadata. This cleans up the organization, as all files in inputs/ are those provided by the user before running the pipeline. It also prevents the file from being overwritten when multiple rounds of QC are done with different parameters, and makes it easier to associate a particular metadata.QC_applied.txt file with the round of QC that produced it.
Note that the truth checksum file in the test data repo was changed to reflect this, so branches without this merge will no longer pass tests.

Move qc'ed metadata output

---

.github/workflows/tests.yml

Mambaforge is being sunsetted, so we have to switch to miniforge3 for the github workflows. Not sure if this will fix the problems in build.yml as well.
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/

Try miniforge

---

.github/workflows/build.yml
.github/workflows/tests.yml
Dockerfile
workflow/envs/base.yml
workflow/envs/reports.yml

Mambaforge is being sunsetted, so test workflow file had to be updated to use miniforge. This caused tests to fail for other reasons, which have been resolved by:
- renaming environment specified in base.yml from base to rodaf_base
- unpinning r-matrixstats package
- replacing "mamba run" with "conda run" in docker file.
Hopefully with these changes, test and build workflows will continue working for a while!

Change github workfows from mambaforge to miniforge

---

Rmd/go_pathway_report.Rmd
workflow/envs/reports.yml

Report was failing because clusterProfiler functions don't properly download KEGG data. Syed previously changed it to use a file downloaded from KEGG medicus, but that solution wasn't great. Here, I use the KEGGREST package to connect to KEGG and download the necessary information, depending on the organism used in the study. This is more flexible.
Still to do: rearrange and simplify the report.

Update ORA and GSEA report

---

install.R
workflow/envs/base.yml
workflow/envs/preprocessing.yml
workflow/envs/reports.yml
workflow/envs/temposeqr.yml

Remove default channel from environment defining yamls, to avoid using proprietary packages from anaconda.
Tested installing environment and running temposeq test dataset on VM without problems.

Delete default channel
